### ISSUE TITLE
Create reference between measurement and provenance data in provenance DB

### ISSUE THREAD

**Issue by Krymnos** [Krymnos/Provenance-System-for-IoT#4]

**Comment by mukrram-bajwa** [comment]
Each data value is assigned the same identifier as its corresponding provenance Datapoint. I pushed changes to the master branch.

So, now the messages in the IOT pipeline will carry a single identifier and that is the same for corresponding Provenance Datapoint. The identifier is unique for each data value and is automatically generated by using Timestamp value, counter and the node identifier. 

The identifier is a 10 Byte Hexadecimal value, where first 4 Bytes represent timestamp, next 3 Bytes counter value and the last 3 Bytes represent the node.
